### ISSUE TITLE
uneven image dimension causes crash in Mac during downsampling

### ISSUE THREAD

**Issue by SlicerMorph** [pieper/SlicerImageStacks#2]
Appears to be impacting only macs as far as I can tell

**Comment by SlicerMorph** [comment]
Actually happens on windows too. Here is the log:

Traceback (most recent call last):
  File "C:/Users/murat/Desktop/SlicerMorph1-3/bin/../SlicerMorph1-3-Extensions/SlicerMorph/lib/Slicer-4.11/qt-scripted-modules/ImageStacks.py", line 235, in onLoadButton
    self.logic.loadByPaths(paths, self.currentNode(), properties)
  File "C:/Users/murat/Desktop/SlicerMorph1-3/bin/../SlicerMorph1-3-Extensions/SlicerMorph/lib/Slicer-4.11/qt-scripted-modules/ImageStacks.py", line 331, in loadByPaths
    volumeArray[sliceIndex] = sliceArray
ValueError: could not broadcast input array from shape (120,144) into shape (119,143)

**Comment by SlicerMorph** [comment]
Sample stack to replicate.

[cropped_odd.zip](https://github.com/pieper/SlicerImageStacks/files/4228896/cropped_odd.zip)

**Comment by pieper** [comment]
I think it's just coincidence that this was only seen on mac, since the logic would be true on all platforms.
